
Vagrant.configure("2") do |config|
    # Pick a box that has a VirtualBox provider for arm64
    config.vm.box = "bento/debian-11"
    config.vm.synced_folder ".", "/vagrant"
  
    # ---------- Server ----------
    config.vm.define "aoustaniSS" do |ser|
      ser.vm.hostname = "aoustaniSS"
      ser.vm.network "private_network", ip: "192.168.56.110"  # as required
      ser.vm.provision "shell", path: "scriptS.sh"
  
      ser.vm.provider "virtualbox" do |vb|
        vb.cpus   = 1
        vb.memory = 1024
        vb.name   = "aoustaniSS"
        # vb.gui = true   # uncomment if you want a window
      end
    end
end
