
# Vagrantfile — VirtualBox (Apple Silicon)
Vagrant.configure("2") do |config|
  # Pick a box that has a VirtualBox provider for arm64
  config.vm.box = "bento/debian-11"

  # ---------- Server ----------
  config.vm.define "aoustaniS" do |ser|
    ser.vm.hostname = "aoustaniS"
    ser.vm.network "private_network", ip: "192.168.56.110"  # as required
    ser.vm.provision "shell", path: "scriptS.sh"

    ser.vm.provider "virtualbox" do |vb|
      vb.cpus   = 1
      vb.memory = 1024
      vb.name   = "aoustaniS"
      # vb.gui = true   # uncomment if you want a window
    end
  end

  # ---------- Worker ----------
  config.vm.define "aoustaniW" do |wor|
    wor.vm.hostname = "aoustaniW"
    wor.vm.network "private_network", ip: "192.168.56.111"  # as required
    wor.vm.provision "shell", path: "scriptW.sh"
    
    wor.vm.provider "virtualbox" do |vb|
      vb.cpus   = 1
      vb.memory = 1024
      vb.name   = "aoustaniW"
      # vb.gui = true
    end
  end
end
