
Vagrant.configure("2") do |config|
    # Pick a box that has a VirtualBox provider for arm64
    config.vm.box = "bento/debian-11"
    config.vm.synced_folder ".", "/vagrant"
  
    # ---------- Server ----------
    config.vm.define "aoustani" do |ser|
      ser.vm.hostname = "aoustani"
      # ser.vm.network "private_network", ip: "192.168.56.110"  # as required
      ser.vm.provision "shell", path: "script.sh"
	config.vm.network "forwarded_port", guest: 8080, host: 8080
	config.vm.network "forwarded_port", guest: 8888, host: 8888

  
      ser.vm.provider "virtualbox" do |vb|
        vb.cpus   = 2
        vb.memory = 4096
        vb.name   = "aoustani"
        # vb.gui = true   # uncomment if you want a window
      end
      
    end
end
# Vagrantfile part 3 
